games/urls.py
from django.urls import path

from . import views

app_name = 'games'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.CreateGame.as_view(), name='create_game'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/setup', views.setup_view, name='setup'),
    path('<int:pk>/main', views.open_main, name='main'),
    path('<int:pk>/end_game', views.end_game, name='end_game'),

    path('<int:pk>/ajax/status_gamers/', views.status_gamers, name='status_gamers'),
    path('<int:pk>/ajax/color_misterx/', views.color_misterx, name='color_misterx'),
    path('<int:pk>/ajax/test_city/', views.test_city, name='test_city'),
    path('<int:pk>/ajax/save_city/', views.save_city, name='save_city'),
    path('<int:pk>/ajax/setting_roles/', views.setting_roles, name='setting_roles'),
    path('<int:pk>/ajax/get_role/', views.get_role, name='get_role'),
    path('<int:pk>/ajax/change_queue/', views.change_queue, name='change_queue'),
    path('<int:pk>/ajax/test_queue/', views.test_queue, name='test_queue'),
    path('<int:pk>/ajax/add_step_of_misterx/', views.add_step_of_misterx, name='add_step_of_misterx'),
    path('<int:pk>/ajax/change_detectives_info/', views.change_detectives_info, name='change_detectives_info'),

    path('<int:pk>/ajax/get_steps_of_misterx/', views.get_steps_of_misterx, name='get_steps_of_misterx'),
    path('<int:pk>/ajax/get_tickets/', views.get_tickets, name='get_tickets'),
    path('<int:pk>/ajax/get_queue/', views.get_queue, name='get_queue'),
    path('<int:pk>/ajax/get_positions/', views.get_positions, name='get_positions'),
    path('<int:pk>/ajax/check_move_player/', views.check_move_player, name='check_move_player'),
    path('<int:pk>/ajax/remove_tickets/', views.remove_tickets, name='remove_tickets'),
    path('<int:pk>/ajax/complite_course/', views.complite_course, name='complite_course'),
    path('<int:pk>/ajax/get_evidences/', views.get_evidences, name='get_evidences'),
    path('<int:pk>/ajax/get_color_misterx/', views.get_color_misterx, name='get_color_misterx'),
    path('<int:pk>/ajax/check_end/', views.check_end, name='check_end'),
    path('<int:pk>/ajax/get_colors/', views.get_colors, name='get_colors'),
    path('<int:pk>/ajax/clear_special_tickets/', views.clear_special_tickets, name='clear_special_tickets'),
    path('<int:pk>/ajax/get_special_tickets/', views.get_tickets_for_special_act, name='get_tickets_for_special_act'),
    path('<int:pk>/ajax/add_special_tickets/', views.add_special_tickets, name='add_special_tickets'),
    path('<int:pk>/ajax/double_step/', views.double_step, name='double_step'),
    path('<int:pk>/ajax/secret_step/', views.secret_step, name='secret_step'),
    path('<int:pk>/ajax/addition_step/', views.addition_step, name='addition_step'),
    path('<int:pk>/ajax/search_step/', views.search_step, name='search_step'),

    path('<int:pk>/ajax/get_possible_steps/', views.get_possible_steps, name='get_possible_steps'),
    path('<int:pk>/ajax/add_message/', views.add_message, name='add_message'),
    path('<int:pk>/ajax/get_chat/', views.get_chat, name='get_chat'),
]

misterx/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
    path('games/', include('games.urls')),
    path('accounts/profile/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
]

games/forms.py
from django import forms

from django.utils import timezone
from datetime import timedelta

from .models import Game


class CreateGameForm(forms.Form):
    game_name = forms.CharField(label="Name of game")
    max_count_players = forms.IntegerField(initial=2, max_value=6, min_value=2)

    def save(self, form):
        cd = form.cleaned_data
        game = Game.objects.create(game_name=cd['game_name'],
                                   max_count_players=cd['max_count_players'],
                                   finish_date=timezone.now() + timedelta(hours=3000),
                                   create_date=timezone.now()
                                   )
        game.save()

games/views.py
from random import randint
from itertools import product
import logging as log
from pprint import pprint

from django.views import generic
from django.views.generic.edit import FormView
from django.shortcuts import render, get_object_or_404
from django.http import Http404, JsonResponse

from django.utils import timezone

from .models import Game, GamersInGame
from .forms import CreateGameForm
from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from . import generation
from . import validate_action
from . import steps
from . import translation_text

log.basicConfig(
        level='INFO',
        format='%(asctime)s %(name)s  %(levelname)s  %(filename)s  %(funcName)s  --> %(message)s',
        filename='./misterx.log',
        filemode='a',
        )


@method_decorator(login_required, name='dispatch')
class IndexView(generic.ListView): #test
    template_name = 'games/index.html'
    context_object_name = 'game_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(translation_text.get_context_for_navbar())
        context.update(translation_text.get_context_for_index())
        return context

    def get_queryset(self):
        return Game.objects.filter(
                create_date__lte=timezone.now()).order_by('-create_date')


@method_decorator(login_required, name='dispatch')
class DetailView(generic.DetailView): #test
    model = Game
    template_name = 'games/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(translation_text.get_context_for_navbar())
        context.update(translation_text.get_context_for_detail_game())
        return context

    def get_queryset(self):
        return Game.objects.filter(
                create_date__lte=timezone.now()).order_by('-create_date')


@method_decorator(login_required, name='dispatch')
class CreateGame(FormView): #test
    form_class = CreateGameForm
    success_url = "/games/"
    template_name = "games/createGame.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(translation_text.get_context_for_navbar())
        context.update(translation_text.get_context_for_create_game())
        return context

    def form_valid(self, form):
        form.save(form)
        return super(CreateGame, self).form_valid(form)


@login_required
def open_main(request, pk, **kwargs):
    game = Game.objects.get(id=pk)
    if game.start_setting_status == False:
        game.initialization()

    context = {
            'game': game
            }
    context.update(translation_text.get_context_for_main())

    return render(request, 'games/gameField.html', context)

@login_required
def end_game(request, pk, **kwargs):
    game = Game.objects.get(id=pk)
    win = {(True, False): 'misterx', (False, True): 'detectives', (True, True): 'detectives', (False, False): 'nobody'}[(validate_action.validate_win_misterx(game), validate_action.validate_win_detectives(game))]

    context = {
            'win': win,
            'city': game.get_cities['misterx']['white'],
            'game': game
            }
    context.update(translation_text.get_context_for_navbar())
    context.update(translation_text.get_context_for_end())

    return render(request, 'games/endGame.html', context)


@login_required
def setup_view(request, pk, **kwargs): #test
    template_name = "games/setupGamePage.html"
    game = get_object_or_404(Game, id=pk)
    if game.create_date <= timezone.now() <= game.finish_date:
        gamer = request.user
        game.add_gamer(gamer)

        ging = GamersInGame.objects.get(game=game, gamer=gamer)
        colors = ['green', 'yellow', 'orange']
        context={
            'game': game,
            'pk': pk,
            'options': ['None', 'I-am-ready'],
            'role': ging.role,
            'colors': [
                (color, translation_text.translate_color(color))
                for color in colors ],
            'color_misterx': ging.color_misterx,
            'players': [gamer.id for gamer in game.gamers.all()],
            }
        context.update(translation_text.get_context_for_navbar())
        context.update(translation_text.get_context_for_setup())

        return render(request,
                template_name=template_name,
                context=context,
                )
    else:
        raise Http404("Game does not exist")


@login_required
def status_gamers(request, pk, **kwargs):#+
    if request.method == 'GET':
        game = get_object_or_404(Game, pk=pk)

        usernames = [(lobby.gamer.id, lobby.gamer.username)
                for lobby in GamersInGame.objects.filter(game=pk)]
        data = {
                'players': [(
                    lobby.gamer.id, 
                    lobby.ready,
                    lobby.role,
                    lobby.gamer==request.user,
                    lobby.gamer.gender,
                    )
                    for lobby in GamersInGame.objects.filter(game=pk)],
                'max_count': game.max_count_players,
                'usernames': usernames,
                }
        log.info(data)
        return JsonResponse(data)

    elif request.method == 'POST':
        gamer = request.user
        game = get_object_or_404(Game, pk=pk)
        ging = GamersInGame.objects.get(game=game, gamer=gamer)
        if request.POST.get('status', None) == "I-am-ready":
            ging.ready = True
            ging.save()
        if request.POST.get('status', None) in {"Yes", "Да"}:
            ging.role = 'misterx'
            ging.save()
        data = {'success': True, 'role': ging.role, 'ready': ging.ready}
        log.info(data)
        return JsonResponse(data)
    raise Http404

@login_required
def color_misterx(request, pk, **kwargs):
    if request.method == 'POST':
        game = get_object_or_404(Game, pk=pk)
        gamer = request.user
        ging = GamersInGame.objects.get(game=game, gamer=gamer)
        color = translation_text.translate_color(request.POST.get('color', None))
        ging.color_misterx = color
        ging.save()

        data = {'success': True, 'color_misterx': ging.color_misterx}
        log.info(data)
        return JsonResponse(data)
    raise Http404

@login_required
def setting_roles(request, pk, **kwargs): # Perhaps, I can delete it. setting_games has the best analog
    if request.method == 'POST':
        game = get_object_or_404(Game, pk=pk)
        if game.count_gamers_misterx == 0:
            misterx = randint(0, game.count_gamers-1)
            for i, gamer in enumerate(game.gamers.all()):
                ging = GamersInGame.objects.get(game=game, gamer=gamer)
                if i == misterx:
                    ging.role = 'misterx'
                    ging.save()
                else:
                    ging.role = 'detectives'
                    ging.save()
            log.info(ging)
        elif game.count_gamers_misterx >= 2:
            misterx = randint(0, game.count_gamers_misterx-1)
            players = [player for player in game.gamers.all()
                    if GamersInGame.objects.get(game=game, gamer=player).role_misterx == True]
            for i, gamer in enumerate(players):
                ging = GamersInGame.objects.get(game=game, gamer=gamer)
                if i == misterx:
                    ging.role = 'misterx'
                    ging.save()
                else:
                    ging.role = 'detectives'
                    ging.save()
            log.info(ging)
        data = {'success': True}
        return JsonResponse(data)
    raise Http404

@login_required
def test_city(request, pk, **kwargs): # This code need to correct and update ????
    if request.method == 'POST':
        game = get_object_or_404(Game, pk=pk)
        user = request.user
        city = request.POST.get('city', None)
        ging = GamersInGame.objects.get(game=game, gamer=user)
        cities = game.get_cities
        if ging.role == 'misterx':
            if city in list(cities['detectives'].values()):
                data = {'result': 'false', 'city': city}
                # Мистер Х прoиграл
                print('------------------END------------------')
            else:
                data = {'result': 'true'}
        else:
            if city in list(cities['misterx'].values()):
                data = {'result': 'false', 'city': city}
                # ход невозможен
            else:
                data = {'result': 'true'}
                #color = request.POST.get('color')
                #game.change_cities(color=color, city=city, role='detectives')
        log.info(data)
        return JsonResponse(data)
    raise Http404

@login_required
def get_role(request, pk, **kwards): #test
    if request.method == 'GET':
        game = get_object_or_404(Game, pk=pk)
        gamer = request.user
        ging = GamersInGame.objects.get(game=game, gamer=gamer)
        role = ging.role
        data = {'role': role}
        log.info(data)
        return JsonResponse(data)
    raise Http404

@login_required
def save_city(request, pk, **kwards):
    if request.method == 'POST':
        game = get_object_or_404(Game, pk=pk)
        color = request.POST.get('color', None)
        city = request.POST.get('city', None)
        user = request.user
        ging = GamersInGame.objects.get(game=game, gamer=user)

        role = ging.role # I deleted the part of code because it is unnecessary now
        game.change_city(color=color, city=city, role=role)

templates/games/createGame.html
<!DOCTYPE html>
<html>
	<head>
		{% load static %}
		{% load i18n %}
		<link rel="shortcut icon" href="{% static 'img/mx.png' %}" type="image/png">
		<link rel="stylesheet" type="text/css" href="{% static 'global_style/nav_style.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'global_style/global_style.css' %}" />
		<meta charset="UTF-8">
		<title>{{ tag_new_game }}</title>
	</head>
	<body>
		<ul class="navbar">
			<li class="navbar"><a href="/">{{ tag_home }}</a></li>
			<li class="navbar"><a class="active" href="/games">{{ tag_games }}</a></li>
			<li class="navbar"><a href="/accounts/profile">{{ tag_profile }}</a></li>
			<li class="navbar"><a href="/accounts/logout">{% trans "Log out" %}</a></li>
		</ul>


		<div id="container">
			<h3>{{ tag_new_game }}</h3>
			<form action="" method="post">
				{% csrf_token %}
				<div class="second_div second_column">
					<div >
						<p>
							{{ tag_game_title }}
							{{form.game_name}}
						</p>
						<p>
							{{ tag_numbers }}
							{{form.max_count_players}}
						</p>
					</div>
				</div>
					<hr>

				<button type="submit">{{ tag_create }}</button>
				<button type="reset">{{ tag_reset }}</button>
			</form>
		</div>
	</body>
</html>

templates/games/detail.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		{% load static %}
		{% load i18n %}
		<title>{{ tag_detail }}</title>
		<link rel="shortcut icon" href="{% static 'img/mx.png' %}" type="image/png">
		<link rel="stylesheet" type="text/css" href="{% static 'global_style/nav_style.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'global_style/global_style.css' %}" />
	</head>
	<body>
		<h1>{{ tag_detail }}</h1>
		<ul class="navbar">
			<li class="navbar"><a href="/">{{ tag_home }}</a></li>
			<li class="navbar"><a class="active" href="/games">{{ tag_games }}</a></li>
			<li class="navbar"><a href="/accounts/profile">{{ tag_profile }}</a></li>
			<li class="navbar"><a href="/accounts/logout">{% trans "Log out" %}</a></li>
		</ul>
		<div id="container">
			<h1>{{game.game_name}}</h1>
			<p> {{ tag_created }}: {{game.create_date}}</p>
			<p> {{ tag_finished }}: {{game.finish_date}}</p>
			{% if error_message %}
			<p><strong>{{ error_message }}</strong></p>
			{% endif %}
			<p>{{ tag_number }}: {{game.count_gamers}}</p>
			<p>{{ tag_max }}: {{game.max_count_players}}</p>
			<hr>
			{% if game.can_gamers_add == True or request.user in game.gamers.all %}
			<a href="{% url 'games:setup' game.id %}">{{ tag_take_part }}</a>
			<p style="text-align: center; font-size: 11pt;">Принимая участие в игре, Вы подтверждаете, что прочитали <a href='/rules'>правила</a> и ознакомились с <a href='/specialActs'>инструкцией по специальным действиям</a>.</p>
			{% else %}
			<p>You will not be added to this game. </p>
			{% endif %}

			<hr>
			<script>
				function openRules(){
					window.open('/rules');
				}
				function openInstructions(){
					window.open('/specialActs');
				}
			</script>
			<p class='insideContainer'>
				<input type='button' onclick='openRules()' value='Правила игры'>
				<input type='button' onclick='openInstructions()' value='Справка по специальным действиям'>
			</p>
				<p style="text-align: center; font-size: 14pt;">Чтобы посмотреть номер города, нужно кликнуть рядом с ним!</p>
		</div>
	</body>
</html>

templates/games/endGame.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
		{% load i18n %}
    <meta charset="UTF-8">
		<link rel="shortcut icon" href="{% static 'img/mx.png' %}" type="image/png">
		<title>{{ tag_end }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'global_style/nav_style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'global_style/global_style.css' %}" />
</head>
<body>
	<h1>{{ tag_end }}</h1>
    <ul class="navbar">
				<li class="navbar"><a href="/">{{ tag_home }}</a></li>
				<li class="navbar"><a class="active" href="/games">{{ tag_games }}</a></li>
				<li class="navbar"><a href="/accounts/profile">{{ tag_profile }}</a></li>
				<li class="navbar"><a href="/accounts/logout">{% trans "Log out" %}</a></li>
    </ul>
    <div id="container">
        <h1>{{ game.game_name }}</h1>
				<p>{{ tag_finish }}<p>
				<h3>{{ tag_win }}  {{ win }}</h3>
				<p>{{ tag_position }} {{ city }}</p>
    </div>
</body>
</html>

templates/games/index.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		{% load static %}
		{% load i18n %}
		<title>{{ tag_index }}</title>
		<link rel="shortcut icon" href="{% static 'img/mx.png' %}" type="image/png">
		<link rel="stylesheet" type="text/css" href="{% static 'global_style/nav_style.css' %}" >
		<link rel="stylesheet" type="text/css" href="{% static 'global_style/global_style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'games/style_index.css' %}">
		<body>
			<h1>{{ tag_index }}</h1>
			<ul class="navbar">
				<li class="navbar"><a href="/">{{ tag_home }}</a></li>
				<li class="navbar"><a class="active" href="/games">{{ tag_games }}</a></li>
				<li class="navbar"><a href="/accounts/profile">{{ tag_profile }}</a></li>
				<li class="navbar"><a href="/accounts/logout">{% trans "Log out" %}</a></li>
			</ul>
			<div id="container">
				<h3>{{ tag_index }}</h3>
				<hr>
				<table class="games">
					<tr><td class="games">
							<a class="games" id="create_game" href="{% url 'games:create_game' %}">{{ tag_create }}</a>
						</td></tr>
				</table>
				<hr>
				{% if game_list %}
				<table class="games">
					{% for game in game_list %}
					<tr>
						<td class="games">
							<a href="{% url 'games:detail' game.id %}">{{ game.game_name }}</a>
						</td>
						<td class="games">
							{% if game.can_gamers_add == True %}
							<div class="status_game">..</div>
							{% else %}
							<div class="status_game">f</div>
							{% endif %}
						</td>
					</tr>
					{% endfor %}
				</table>
				{% else %}
				<p>{{ tag_empty }}</p>
				{% endif %}

			</div>
		</body>
</html>

templates/games/setupGamePage.html
<!DOCTYPE html>
<html>
	<head>
		{% load static %}
		{% load i18n %}
		<link rel="shortcut icon" href="{% static 'img/mx.png' %}" type="image/png">
		<meta charset="UTF-8">
		<title>Setup game</title>
		{% block stylesheet %}
		<link rel="stylesheet" type="text/css" href="{% static 'global_style/nav_style.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'global_style/global_style.css' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static 'games/style_setup.css' %}">
		{% endblock %}
		<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
		{% csrf_token %}

	</head>
	<body onload="init()">
		<ul class="navbar">
			<li class="navbar"><a href="/">{{ tag_home }}</a></li>
			<li class="navbar"><a class="active" href="/games">{{ tag_games }}</a></li>
			<li class="navbar"><a href="/accounts/profile">{{ tag_profile }}</a></li>
			<li class="navbar"><a href="/accounts/logout">{% trans "Log out" %}</a></li>
		</ul>
		<div id="container">
			<h1>{{ game.game_name }}</h1>
			<hr>
			<div id="tableRole" class="second_div">
				<p>{{ tag_login }} <i style="color: #5faf00">{{request.user}}</i>.</p>
				{% if role == 'misterx' %}
				<p id="thColor"><b>{{ tag_color }}:</b>
					{% else %}
					<p id="thColor" hidden><b>{{ tag_color }}:</b>
						{% endif %}
						<select id='color_misterx'>
							{% for color, translate_color in colors %}
							{% if color_misterx == color %}
							<option id={{color}} seleted>{{ translate_color }}</option>
							{% else %}
							<option id={{color}}>{{ translate_color }}</option>
							{% endif %}
							{% endfor %}
						</select></p>

						<div class="third_div">
							<table id='table' class="gamers">
								<tr>
									<th>{{ tag_gamer }}</th><th>{{ tag_status }}</th><th>{{ tag_desire }}</th>
								</tr>
								{% for gamer in game.gamers.all %}
								<tr>
									<td class="gamers">{{gamer}}</td>
									<td id="gamer{{gamer.id}}" class="status">
										{% if gamer == request.user %}
										<select id="in_status">
											{% for opt in options %}
											<option id="{{ opt }}">{{ opt }}</option>
											{% endfor %}
										</select>
										{% else %}
											{% if gamer.gender == "woman" %}
												<i>{{ tag_not_ready_w }}</i>
											{% else %}
												<i>{{ tag_not_ready }}</i>
											{% endif %}
										{% endif %}
									</td>
									<td id="misterx{{gamer.id}}" class="misterx">
										{% if gamer == request.user %}
										<select id="in_want">
											<option id="No">{% trans "No" %}</option>
											<option id="Yes">{% trans "Yes" %}</option>
										</select>
										{% else %}
										<i>{% trans "No" %}</i>
										{% endif %}
									</td>
								</tr>

								{% endfor %}
							</table>
						</div>
			</div>
			<hr>
			<script>
				function openRules(){
					window.open('/rules');
				}
				function openInstructions(){
					window.open('/specialActs');
				}
			</script>
			<p class='insideContainer'>
				<input type='button' onclick='openRules()' value='Правила игры'>
				<input type='button' onclick='openInstructions()' value='Справка по специальным действиям'>
			</p>
		</div>
		{% block javascript %}
		<script>
			function init() {
				document.getElementById('{{color_misterx}}').selected = true;
			}
			var players = {{ players }};

			$(function (){
				var gamer_id = {{request.user.id}};
				var csrftoken = $("[name=csrfmiddlewaretoken]").val();
				function csrfSafeMethod(method) {
					// these HTTP methods do not require CSRF protection
					return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
				}
				$.ajaxSetup({
					beforeSend: function(xhr, settings) {
						if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
							xhr.setRequestHeader("X-CSRFToken", csrftoken);
						}
					}
				});

				function addNewPlayer(player, usernames) {
					var username;
					for (p of usernames) {
						if (p[0] == player[0])
							username = p[1];
					}

					var resTag = `<tr>
					<td class='gamers'>${username}</td>
					<td id="gamer${player[0]}" class="status">
								<i>${player[1] ? (player[4] == 'woman' ? '{{ tag_ready_w }}' : '{{ tag_ready }}')
										: (player[4] == 'woman' ? '{{ tag_not_ready_w }}': '{{ tag_not_ready }}') }</i>
									</td>
									<td id="misterx${player[0]}" class="misterx">
										<i>${(player[2] == 'misterx' ? '{% trans "Yes" %}' : '{% trans "No" %}')}</i>
									</td>
								</tr>
				`
					$('#table').append(resTag);
					players.push(player[0]);
				};

				function poll() {
					$.get('ajax/status_gamers/', function(data){
						var countReady = 0;
						for(player of data.players) {
							if (players.indexOf(player[0]) == -1) {
								addNewPlayer(player, data.usernames);
							} else {
								if(player[1]) {
									console.info('#gamer' + player[0]);
									$('#gamer' + player[0]).html(
										(player[4] == 'woman' ? '{{ tag_ready_w }}' : '{{ tag_ready }}') +'!');
									countReady += 1;
								}
								if(player[2] == "misterx") {
									console.info('#misterx' + player[0]);
									$('#misterx' + player[0]).html('{% trans "Yes" %}');

									if (player[3] == true){
										document.getElementById("thColor").hidden = false;
									}
								}
							}
						}
						if (data.max_count == countReady){
							window.location.href = "{% url 'games:main' game.id %}";
						}
						else {
							setTimeout(poll, 5000);
						}


					});
				};
				poll();

				$("#in_status").on('change', function () {
					var status = $(this).val();
					$.post({
						url: 'ajax/status_gamers/',
						data: {
							'status': status,
						},
						dataType: 'json',
						success:
						function (data) {
							console.info('Success send status ready', data);
						}
					});
				});
				$("#in_want").on('change', function () {
					var status = $(this).val();
					$.post({
						url: 'ajax/status_gamers/',
						data: {
							'status': status,
						},
						dataType: 'json',
						success:
						function (data) {
							console.info("Success send status MX", data);
							if (data["role"] == true){
								document.getElementById("thColor").hidden = false;
							}
							else {
								$("#thColor").hidden = true;
							}
						}
					});
				});
				$("#color_misterx").on('change', function () {
					var color = $(this).val();
					console.log(color);
					$.post({
						url: 'ajax/color_misterx/',
						data: {
							'color': color,
						},
						dataType: 'json',
						success:
						function (data) {
							console.info('Success send color MX', data);
						}
					});
				});
			});
		</script>
		{% endblock %}
	</body>
</html>